### ISSUE TITLE
Builds fail on 32 bit architectures

### ISSUE THREAD

**Issue by nullr0ute** [fedora-iot/clevis-pin-tpm2#2]
Seeing the following issue when building on ARMv7/i686:

<pre>
     Running `/usr/bin/rustc --crate-name clevis_pin_tpm2 --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -Cembed-bitcode=no -C metadata=9bc4e67ce1c71e36 -C extra-filename=-9bc4e67ce1c71e36 --out-dir /builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/deps -L dependency=/builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/deps --extern atty=/builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/deps/libatty-f440bfb5aecb778a.rlib --extern base64=/builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/deps/libbase64-3bfab91a3582a27a.rlib --extern biscuit=/builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/deps/libbiscuit-108f7cb8321d374f.rlib --extern serde=/builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/deps/libserde-369ee0f1c6e361fd.rlib --extern serde_json=/builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/deps/libserde_json-2f96bad1a84bf24d.rlib --extern tpm2_policy=/builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/deps/libtpm2_policy-0a56f631a7ec1c63.rlib --extern tss_esapi=/builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/deps/libtss_esapi-06ee2eb81288b15e.rlib -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now -Ccodegen-units=1 --cap-lints=warn -L native=/builddir/build/BUILD/clevis-pin-tpm2-0.1.1/target/release/build/ring-e8b5478973bc54c5/out -L native=/usr/lib -L native=/usr/lib -L native=/usr/lib`
error[E0308]: mismatched types
  --> src/tpm_objects.rs:69:13
   |
69 |             resp.capacity() as u64,
   |             ^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
   |
help: you can convert an `u64` to `u32` and panic if the converted value wouldn't fit
   |
69 |             (resp.capacity() as u64).try_into().unwrap(),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0308]: mismatched types
  --> src/tpm_objects.rs:70:13
   |
70 |             &mut offset,
   |             ^^^^^^^^^^^ expected `u32`, found `u64`
   |
   = note:    expected raw pointer `*mut u32`
           found mutable reference `&mut u64`
error[E0308]: mismatched types
  --> src/tpm_objects.rs:91:13
   |
91 |             resp.capacity() as u64,
   |             ^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
   |
help: you can convert an `u64` to `u32` and panic if the converted value wouldn't fit
   |
91 |             (resp.capacity() as u64).try_into().unwrap(),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0308]: mismatched types
  --> src/tpm_objects.rs:92:13
   |
92 |             &mut offset,
   |             ^^^^^^^^^^^ expected `u32`, found `u64`
   |
   = note:    expected raw pointer `*mut u32`
           found mutable reference `&mut u64`
error[E0308]: mismatched types
   --> src/tpm_objects.rs:112:13
    |
112 |             val.len() as u64,
    |             ^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
help: you can convert an `u64` to `u32` and panic if the converted value wouldn't fit
    |
112 |             (val.len() as u64).try_into().unwrap(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0308]: mismatched types
   --> src/tpm_objects.rs:113:13
    |
113 |             &mut offset,
    |             ^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note:    expected raw pointer `*mut u32`
            found mutable reference `&mut u64`
error[E0308]: mismatched types
   --> src/tpm_objects.rs:133:13
    |
133 |             val.len() as u64,
    |             ^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |
help: you can convert an `u64` to `u32` and panic if the converted value wouldn't fit
    |
133 |             (val.len() as u64).try_into().unwrap(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0308]: mismatched types
   --> src/tpm_objects.rs:134:13
    |
134 |             &mut offset,
    |             ^^^^^^^^^^^ expected `u32`, found `u64`
    |
    = note:    expected raw pointer `*mut u32`
            found mutable reference `&mut u64`
error: aborting due to 8 previous errors
For more information about this error, try `rustc --explain E0308`.
</pre>

**Comment by puiterwijk** [comment]
This should be fixed in b7f8d115a73381b4eba319ef8989f32c0a5d08af.
